# Generated by Django 4.2 on 2023-04-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menus', '0002_menunode_is_named_url_menunode_text_menunode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('root_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree_menus.menunode')),
            ],
        ),
    ]
