# Generated by Django 4.2 on 2023-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menus', '0004_alter_menunode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunode',
            name='url',
            field=models.CharField(blank='', max_length=500),
        ),
    ]
